// Karnataka Cities List - All major district HQs and cities
export const KARNATAKA_CITIES = [
  "Bengaluru",
  "Bengaluru Rural",
  "Mysuru",
  "Mangaluru",
  "Hubballi",
  "Dharwad",
  "Belagavi",
  "Kalaburagi",
  "Ballari",
  "Davanagere",
  "Shivamogga",
  "Tumakuru",
  "Udupi",
  "Hassan",
  "Mandya",
  "Chitradurga",
  "Kolar",
  "Chikkamagaluru",
  "Vijayapura",
  "Bidar",
  "Raichur",
  "Koppal",
  "Gadag",
  "Bagalkot",
  "Yadgir",
  "Ramanagara",
  "Chikkaballapur",
  "Kodagu (Madikeri)",
  "Haveri",
  "Uttara Kannada (Karwar)",
  "Dakshina Kannada",
  "Chamarajanagar",
] as const;

export type KarnatakaCity = typeof KARNATAKA_CITIES[number];

// API Configuration
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:4000";

// Pagination defaults
export const DEFAULT_PAGE_SIZE = 20;
export const PAGE_SIZE_OPTIONS = [15, 20, 25, 50] as const;

// Mock employee data for fallback
export interface Employee {
  id: string;
  name: string;
  kgid: string;
  role: string;
  yearsOfWork: number;
  dob: string;
  currentCity: string;
  currentPosition: string;
  email?: string;
  phone?: string;
}

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: "1",
    name: "Rajesh Kumar",
    kgid: "KG2019001",
    role: "Senior Clerk",
    yearsOfWork: 12,
    dob: "1985-03-15",
    currentCity: "Bengaluru",
    currentPosition: "Administrative Officer",
  },
  {
    id: "2",
    name: "Priya Sharma",
    kgid: "KG2020045",
    role: "Assistant Engineer",
    yearsOfWork: 8,
    dob: "1990-07-22",
    currentCity: "Mysuru",
    currentPosition: "Junior Engineer",
  },
  {
    id: "3",
    name: "Venkatesh Gowda",
    kgid: "KG2015078",
    role: "Section Officer",
    yearsOfWork: 15,
    dob: "1980-11-08",
    currentCity: "Mangaluru",
    currentPosition: "Deputy Secretary",
  },
  {
    id: "4",
    name: "Lakshmi Devi",
    kgid: "KG2018032",
    role: "Accounts Officer",
    yearsOfWork: 10,
    dob: "1988-01-25",
    currentCity: "Hubballi",
    currentPosition: "Senior Accountant",
  },
  {
    id: "5",
    name: "Mohammed Farooq",
    kgid: "KG2017089",
    role: "Technical Assistant",
    yearsOfWork: 9,
    dob: "1989-05-12",
    currentCity: "Belagavi",
    currentPosition: "Technical Officer",
  },
  {
    id: "6",
    name: "Shivanna Reddy",
    kgid: "KG2016054",
    role: "District Officer",
    yearsOfWork: 14,
    dob: "1982-09-30",
    currentCity: "Kalaburagi",
    currentPosition: "Deputy Commissioner",
  },
  {
    id: "7",
    name: "Anitha Kumari",
    kgid: "KG2021012",
    role: "Data Entry Operator",
    yearsOfWork: 4,
    dob: "1995-12-18",
    currentCity: "Ballari",
    currentPosition: "Junior Clerk",
  },
  {
    id: "8",
    name: "Basavaraj Patil",
    kgid: "KG2014098",
    role: "Executive Engineer",
    yearsOfWork: 16,
    dob: "1978-04-05",
    currentCity: "Davanagere",
    currentPosition: "Chief Engineer",
  },
  {
    id: "9",
    name: "Kavitha Nair",
    kgid: "KG2019067",
    role: "Research Officer",
    yearsOfWork: 7,
    dob: "1991-08-14",
    currentCity: "Shivamogga",
    currentPosition: "Senior Researcher",
  },
  {
    id: "10",
    name: "Suresh Babu",
    kgid: "KG2013045",
    role: "Chief Clerk",
    yearsOfWork: 18,
    dob: "1975-02-28",
    currentCity: "Tumakuru",
    currentPosition: "Head Clerk",
  },
  {
    id: "11",
    name: "Deepika Hegde",
    kgid: "KG2022001",
    role: "Junior Engineer",
    yearsOfWork: 2,
    dob: "1998-06-10",
    currentCity: "Udupi",
    currentPosition: "Assistant Engineer",
  },
  {
    id: "12",
    name: "Ravi Shankar",
    kgid: "KG2016023",
    role: "Inspector",
    yearsOfWork: 11,
    dob: "1986-10-03",
    currentCity: "Hassan",
    currentPosition: "Senior Inspector",
  },
  {
    id: "13",
    name: "Meena Kumari",
    kgid: "KG2018076",
    role: "Office Superintendent",
    yearsOfWork: 9,
    dob: "1989-03-22",
    currentCity: "Mandya",
    currentPosition: "Administrative Superintendent",
  },
  {
    id: "14",
    name: "Arun Kumar",
    kgid: "KG2017034",
    role: "Programmer",
    yearsOfWork: 8,
    dob: "1990-11-15",
    currentCity: "Chitradurga",
    currentPosition: "Senior Programmer",
  },
  {
    id: "15",
    name: "Savitha Rao",
    kgid: "KG2015091",
    role: "Librarian",
    yearsOfWork: 13,
    dob: "1983-07-08",
    currentCity: "Kolar",
    currentPosition: "Chief Librarian",
  },
  {
    id: "16",
    name: "Naveen Gowda",
    kgid: "KG2020078",
    role: "Survey Officer",
    yearsOfWork: 5,
    dob: "1993-04-25",
    currentCity: "Chikkamagaluru",
    currentPosition: "Land Surveyor",
  },
  {
    id: "17",
    name: "Rekha Jain",
    kgid: "KG2014056",
    role: "Finance Officer",
    yearsOfWork: 15,
    dob: "1981-12-01",
    currentCity: "Vijayapura",
    currentPosition: "Chief Finance Officer",
  },
  {
    id: "18",
    name: "Siddharth Murthy",
    kgid: "KG2019089",
    role: "Legal Assistant",
    yearsOfWork: 6,
    dob: "1992-09-18",
    currentCity: "Bidar",
    currentPosition: "Legal Officer",
  },
  {
    id: "19",
    name: "Geetha Bhat",
    kgid: "KG2016067",
    role: "Training Officer",
    yearsOfWork: 12,
    dob: "1984-05-30",
    currentCity: "Raichur",
    currentPosition: "Chief Training Officer",
  },
  {
    id: "20",
    name: "Manjunath Shetty",
    kgid: "KG2021034",
    role: "Assistant Director",
    yearsOfWork: 3,
    dob: "1996-01-12",
    currentCity: "Koppal",
    currentPosition: "Deputy Director",
  },
  {
    id: "21",
    name: "Pallavi Kamath",
    kgid: "KG2018045",
    role: "Welfare Officer",
    yearsOfWork: 8,
    dob: "1990-08-07",
    currentCity: "Gadag",
    currentPosition: "Senior Welfare Officer",
  },
  {
    id: "22",
    name: "Harish Kumar",
    kgid: "KG2015023",
    role: "Revenue Inspector",
    yearsOfWork: 14,
    dob: "1982-03-14",
    currentCity: "Bagalkot",
    currentPosition: "Deputy Tahsildar",
  },
  {
    id: "23",
    name: "Suma Devi",
    kgid: "KG2017056",
    role: "Health Officer",
    yearsOfWork: 10,
    dob: "1987-06-22",
    currentCity: "Yadgir",
    currentPosition: "District Health Officer",
  },
  {
    id: "24",
    name: "Kiran Naik",
    kgid: "KG2020012",
    role: "Environment Officer",
    yearsOfWork: 5,
    dob: "1994-10-28",
    currentCity: "Ramanagara",
    currentPosition: "Senior Environment Officer",
  },
  {
    id: "25",
    name: "Vidya Rani",
    kgid: "KG2013078",
    role: "Education Officer",
    yearsOfWork: 17,
    dob: "1977-02-15",
    currentCity: "Chikkaballapur",
    currentPosition: "Deputy Director of Education",
  },
];
