// First Post Held dropdown options
export const FIRST_POST_HELD_OPTIONS = [
  "Assistant Deputy Director",
  "Deputy Director",
  "DTC / RTC Principal",
  "Medical Superdent",
  "District Surgeon",
  "DHO",
  "RCH",
  "District Enforcement Officer",
  "DSO",
  "DTO",
  "District Project Development Officer",
  "District Non Communicable Disease Officer",
  "Specialist",
  "SMO",
  "MO",
  "AAO",
  "Superdent",
  "FDA",
  "SDA",
  "PHCO",
  "HIO",
  "Staff Nurse",
  "Driver",
  "Group D",
] as const;
